# Generated by Django 5.2.1 on 2025-05-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file_path',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
