# Generated by Django 5.1.8 on 2025-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentorprofile_bio_progress_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
