# Generated by Django 5.1.8 on 2025-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_mentorprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
