# Generated by Django 5.1.8 on 2025-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_alter_mentorprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='industry_expertise',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentorship_areas',
            field=models.JSONField(default=[]),
        ),
    ]
