# Generated by Django 5.1.8 on 2025-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_alter_mentorprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='industry_expertise',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentorship_areas',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='qualifications',
            field=models.JSONField(blank=True, null=True, default={}),
        ),
    ]
