# Generated by Django 5.1.8 on 2025-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_alter_mentorprofile_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='skills',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
