# Generated by Django 5.2 on 2025-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0009_alter_mentorprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_acted',
            field=models.BooleanField(default=False),
        ),
    ]
