# Generated by Django 5.2 on 2025-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_alter_budget_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='type',
            field=models.CharField(blank=True, choices=[('ai_suggesstion', 'Ai Suggestion'), ('user_input', 'User input')], default='user_input', null=True),
        ),
    ]
