# Generated by Django 5.1.7 on 2025-04-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
