# Generated by Django 5.1.8 on 2025-04-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='mentor_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessownerprofile',
            name='other_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessownerprofile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='mentorship_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='preferred_mentor_characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
